FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./

COPY rollup.config.js ./

RUN npm install

COPY . .

RUN npm run-script build:local

EXPOSE 5000
EXPOSE 3000

ENV HOST=0.0.0.0

CMD [ "npm", "start" ]




